import argparse
import ctypes

import torch
import torch_npu  # noqa: F401

from ptodsl.npu_info import get_num_cube_cores, get_test_device

_DEFAULT_NUM_CORES = get_num_cube_cores()


def torch_to_ctypes(tensor):
    return ctypes.c_void_p(tensor.data_ptr())


def load_lib(lib_path, block_dim=_DEFAULT_NUM_CORES):
    lib = ctypes.CDLL(lib_path)
    lib.call_kernel.argtypes = [
        ctypes.c_uint32,  # blockDim
        ctypes.c_void_p,  # stream
        ctypes.c_void_p,  # a
        ctypes.c_void_p,  # b
        ctypes.c_void_p,  # c (output)
        ctypes.c_uint32,  # batch
        ctypes.c_uint32,  # n_cols
    ]
    lib.call_kernel.restype = None

    def geglu_func(a, b, c, batch, n_cols, block_dim=block_dim, stream_ptr=None):
        if stream_ptr is None:
            stream_ptr = torch.npu.current_stream()._as_parameter_
        lib.call_kernel(
            block_dim,
            stream_ptr,
            torch_to_ctypes(a),
            torch_to_ctypes(b),
            torch_to_ctypes(c),
            batch,
            n_cols,
        )

    return geglu_func


def geglu_ref(a, b):
    """Reference GEGLU matching the PTO kernel.

    Computes c = gelu_approx(a) * b, where:
        gelu_approx(a) = 0.5 * a * (1 + tanh(a))
        tanh(a)        = (exp(2a) - 1) / (exp(2a) + 1)

    Note: This is a simplified tanh-based GELU (without the polynomial
    inner argument used in the full approximation). It matches what the
    PTO kernel computes using only tile-tile operations.
    """
    a_f32 = a.float()
    gelu_a = 0.5 * a_f32 * (1.0 + torch.tanh(a_f32))
    return gelu_a.to(a.dtype) * b


def test_geglu(lib_path, block_dim=_DEFAULT_NUM_CORES):
    device = get_test_device()
    torch.npu.set_device(device)

    geglu = load_lib(lib_path=lib_path, block_dim=block_dim)

    torch.manual_seed(0)
    dtype = torch.float16
    batch_list = [1, 4, 22, 65]
    n_cols_list = [128, 256, 512, 1024, 2048, 4096, 8192, 16384]

    results = []
    for batch in batch_list:
        for n_cols in n_cols_list:
            # Use small range to stay within fp16 exp range (avoid overflow).
            a = torch.randn(batch, n_cols, device=device, dtype=dtype).clamp(-4, 4)
            b = torch.randn(batch, n_cols, device=device, dtype=dtype)
            c = torch.empty(batch, n_cols, device=device, dtype=dtype)

            y_ref = geglu_ref(a, b)
            geglu(a, b, c, batch, n_cols)
            torch.npu.synchronize()

            is_match = True
            detail = ""
            try:
                torch.testing.assert_close(c, y_ref, rtol=1e-2, atol=1e-2)
            except AssertionError as err:
                is_match = False
                detail = str(err).strip() if str(err) else "assert_close failed"

            status = "match" if is_match else "mismatch"
            print(f"[{status}] batch={batch}, n_cols={n_cols}, lib={lib_path}")
            if detail:
                print("  detail:")
                print(detail)
            results.append((batch, n_cols, status, detail))

    print(f"\ndetailed summary for {lib_path}:")
    for batch, n_cols, status, detail in results:
        msg = f"  batch={batch}, n_cols={n_cols}, status={status}"
        print(msg)
        if detail:
            print("    detail:")
            print(detail)
    return results


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--lib",
        default="./geglu_lib.so",
        help="Path to the shared library generated by compile.sh.",
    )
    parser.add_argument(
        "--block-dim",
        type=int,
        default=_DEFAULT_NUM_CORES,
        help=f"Kernel blockDim (default: {_DEFAULT_NUM_CORES}).",
    )
    args = parser.parse_args()
    test_geglu(args.lib, block_dim=args.block_dim)
